### ISSUE TITLE
getting instant order updates

### ISSUE THREAD

**Issue by adityamertia** [coinbase/coinbase-pro-node#328]
Is there a way to set a handle on an order such that every update for the order is sent automatically. 
2 ways to achieve this are to place the order and 
1) using the orderId to either check status using API 
2) using orderId to filter the websocket data to find status updates on orderId.
The first approach will be too slow for getting status updates and also isn't the recommended approach for status updates (API do block)
In the second approach, there can be chances that the WebSocket data is missed due to delay in starting websocket read.

Is there an alternate preferred way of doing this?

**Comment by vansergen** [comment]
If you have an `id` saved somewhere then you probably submitted the order some time ago. So, if you connect to the websocket then there is a chance that you will not receive updates because your order is settled already. But if you connect to the websocket and after that you submit your order then you will get all updates on ws channel. It seems that the preferred way is to get order updates using REST requests and connect to the websocket to start listening for new updates. If the websocket connection is closed then you just reconnect (and probably make another REST request if you can't reconnect immediately ).

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
